EXENAME = lab_intro
OBJS = main.o png.o rgbapixel.o

CXX = clang++
CXXFLAGS = -std=c++1y -stdlib=libc++ -c -g -O0 -Wall -Wextra -pedantic -I /usr/local/include
LD = clang++
LDFLAGS = -std=c++1y -stdlib=libc++ -lpng -lc++abi -L /usr/local/lib -I /usr/local/include

all : $(EXENAME)

$(EXENAME) : $(OBJS)
	$(LD) $(OBJS) $(LDFLAGS) -o $(EXENAME)

main.o : main.cpp png.h rgbapixel.h
	$(CXX) $(CXXFLAGS) main.cpp

png.o : png.cpp png.h rgbapixel.h
	$(CXX) $(CXXFLAGS) png.cpp

rgbapixel.o : rgbapixel.cpp rgbapixel.h
	$(CXX) $(CXXFLAGS) rgbapixel.cpp

clean :
	-rm -f *.o $(EXENAME)
